# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cU7nTa4cJMPCQo6QQ5oEN8pTrqR8MBU4
"""

sentence = input('Digite seu texto: ') # Entra o texto a ser trabalhado

# CAPTURA O TEXTO E REMOVE AS LETRAS IGUAIS

list_letters = list(sentence) # Cria uma Lista com cada letra da frase
list_key = [] # Lista de letras
list_value = [] # Lista de Contagem
 
for i in list_letters: # para cada letra da lista
   #Ative para ignorar os espaços vazios:
    #if i not in list_key and i != " ": # Se não tiver na lista de impressão
            list_key.append(i) # Adiciona a letra na lista de impressão
        
# CONTANDO AS LETRAS 

for i in list_key: # Para cada caractere na Lista de Letras
    i = sentence.count(i) # Conta quantas vezes a letra aparece
    list_value.append(i) # Adiciona o valor na Lista de Contagem

# ADICIONANDO VALORES NO DICIONARIO

count_letters = dict(zip(list_key, list_value)) # Adicion no Dicionário o INDEX e o VALOR
print('____________________________________________\n')

print('O texto inserido contém:\n')
print(count_letters) # Imprime na tela o Dicionário

